name: Build, Push, and Deploy Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push repo-service
        uses: docker/build-push-action@v4
        with:
          context: ./repo_nha_hang_com_ga_BE
          file: ./repo_nha_hang_com_ga_BE/Dockerfile
          tags: haibui040623/repo-nha-hang-com-ga-be:latest
          push: true

      - name: Build and push auth-service
        uses: docker/build-push-action@v4
        with:
          context: ./auth.service
          file: ./auth.service/Dockerfile
          tags: haibui040623/auth-service:latest
          push: true

      - name: Build and push file-service
        uses: docker/build-push-action@v4
        with:
          context: ./file.service
          file: ./file.service/Dockerfile
          tags: haibui040623/file-service:latest
          push: true

      - name: SSH into server and deploy containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ubuntu/repo_nha_hang_com_ga_BE

            git pull origin main

            echo "MONGO_CONNECTION=${{ secrets.MONGO_CONNECTION }}" > .env
            echo "JWT_KEY=${{ secrets.JWT_KEY }}" >> .env
            echo "EMAIL_HOST=${{ secrets.EMAILSETTINGS }}" >> .env

            docker-compose down
            docker images | grep haibui040623 | awk '{print $3}' | xargs -r docker rmi -f || true
            docker system prune -f

            docker-compose pull

            docker-compose up -d
